FROM debian:13-slim

RUN apt-get update && apt-get install -y ca-certificates

COPY sentry_exporter  /sentry_exporter
COPY sentry_exporter.yml       /sentry_exporter.yml

EXPOSE      9412
ENTRYPOINT  [ "/sentry_exporter" ]
CMD         [ "-config.file=/sentry_exporter.yml" ]
