FROM debian:buster-slim@sha256:557ee531b81ce380d012d83b7bb56211572e5d6088d3e21a3caef7d7ed7f718b

RUN apt-get update && apt-get install -y ca-certificates

COPY sentry_exporter  /sentry_exporter
COPY sentry_exporter.yml       /sentry_exporter.yml

EXPOSE      9412
ENTRYPOINT  [ "/sentry_exporter" ]
CMD         [ "-config.file=/sentry_exporter.yml" ]
